export interface MenuItem {
  id: string;
  name: string;
  type: string;
  price: string;
  rating: number;
  image: any;
  category: string;
  description?: string;
  ingredients?: string[];
  prepTime?: string;
  serves?: string;
  calories?: string;
  isVeg?: boolean;
  isSpicy?: boolean;
}

export const MENU_ITEMS: MenuItem[] = [
  // Biryanis
  {
    id: '1',
    name: 'Chicken Biryani',
    type: 'Hyderabadi Style',
    price: '$12.99',
    rating: 4.8,
    image: require('../assets/biryani1.jpg'),
    category: 'Biryanis',
    description: 'Aromatic basmati rice cooked with tender chicken pieces, fragrant spices, and saffron.',
    ingredients: ['Basmati Rice', 'Chicken', 'Saffron', 'Yogurt', 'Onions', 'Spices'],
    prepTime: '45 mins',
    serves: '2-3 people',
    calories: '650 per serving',
    isVeg: false,
    isSpicy: true,
  },
  {
    id: '2',
    name: 'Mutton Biryani',
    type: 'Lucknowi Style',
    price: '$15.99',
    rating: 4.9,
    image: require('../assets/biryani2.jpg'),
    category: 'Biryanis',
    description: 'Rich and flavorful Lucknowi-style biryani with succulent mutton pieces.',
    ingredients: ['Basmati Rice', 'Mutton', 'Saffron', 'Yogurt', 'Onions', 'Garam Masala'],
    prepTime: '60 mins',
    serves: '2-3 people',
    calories: '720 per serving',
    isVeg: false,
    isSpicy: true,
  },
  {
    id: '3',
    name: 'Veg Biryani',
    type: 'Aromatic Basmati',
    price: '$9.99',
    rating: 4.7,
    image: require('../assets/biryani3.jpg'),
    category: 'Biryanis',
    description: 'Fragrant basmati rice layered with fresh vegetables and aromatic spices.',
    ingredients: ['Basmati Rice', 'Mixed Vegetables', 'Saffron', 'Paneer', 'Cashews', 'Spices'],
    prepTime: '40 mins',
    serves: '2-3 people',
    calories: '550 per serving',
    isVeg: true,
    isSpicy: false,
  },
  {
    id: '4',
    name: 'Prawn Biryani',
    type: 'Coastal Special',
    price: '$16.99',
    rating: 4.8,
    image: require('../assets/biryani4.jpg'),
    category: 'Biryanis',
    description: 'Coastal special biryani featuring fresh prawns and aromatic rice.',
    ingredients: ['Basmati Rice', 'Fresh Prawns', 'Coconut', 'Curry Leaves', 'Coastal Spices'],
    prepTime: '50 mins',
    serves: '2-3 people',
    calories: '680 per serving',
    isVeg: false,
    isSpicy: true,
  },

  // Veg Appetizers
  {
    id: '5',
    name: 'Paneer Tikka',
    type: 'Grilled Cottage Cheese',
    price: '$8.99',
    rating: 4.6,
    image: require('../assets/biryani1.jpg'), // Replace with actual appetizer images
    category: 'Veg Appetizers',
    description: 'Marinated cottage cheese cubes grilled to perfection with bell peppers and onions.',
    ingredients: ['Paneer', 'Bell Peppers', 'Onions', 'Yogurt', 'Spices'],
    prepTime: '20 mins',
    serves: '2-3 people',
    calories: '320 per serving',
    isVeg: true,
    isSpicy: false,
  },
  {
    id: '6',
    name: 'Samosa',
    type: 'Crispy Pastry',
    price: '$4.99',
    rating: 4.5,
    image: require('../assets/biryani2.jpg'),
    category: 'Veg Appetizers',
    description: 'Golden crispy pastry filled with spiced potatoes and green peas.',
    ingredients: ['Potatoes', 'Green Peas', 'Pastry', 'Cumin', 'Coriander'],
    prepTime: '15 mins',
    serves: '1-2 people',
    calories: '180 per piece',
    isVeg: true,
    isSpicy: false,
  },

  // Non Veg Appetizers
  {
    id: '7',
    name: 'Chicken Tikka',
    type: 'Tandoor Grilled',
    price: '$10.99',
    rating: 4.7,
    image: require('../assets/biryani3.jpg'),
    category: 'Non Veg Appetizers',
    description: 'Tender chicken pieces marinated in yogurt and spices, grilled in tandoor.',
    ingredients: ['Chicken', 'Yogurt', 'Ginger-Garlic', 'Red Chili', 'Garam Masala'],
    prepTime: '25 mins',
    serves: '2-3 people',
    calories: '280 per serving',
    isVeg: false,
    isSpicy: true,
  },
  {
    id: '8',
    name: 'Fish Fry',
    type: 'South Indian Style',
    price: '$11.99',
    rating: 4.6,
    image: require('../assets/biryani4.jpg'),
    category: 'Non Veg Appetizers',
    description: 'Fresh fish marinated with South Indian spices and shallow fried.',
    ingredients: ['Fish', 'Turmeric', 'Red Chili', 'Curry Leaves', 'Coconut Oil'],
    prepTime: '20 mins',
    serves: '2 people',
    calories: '350 per serving',
    isVeg: false,
    isSpicy: true,
  },

  // Veg Curries
  {
    id: '9',
    name: 'Dal Tadka',
    type: 'Yellow Lentils',
    price: '$7.99',
    rating: 4.4,
    image: require('../assets/biryani1.jpg'),
    category: 'Veg Curries',
    description: 'Yellow lentils tempered with cumin, mustard seeds, and aromatic spices.',
    ingredients: ['Yellow Dal', 'Cumin', 'Mustard Seeds', 'Turmeric', 'Tomatoes'],
    prepTime: '30 mins',
    serves: '3-4 people',
    calories: '220 per serving',
    isVeg: true,
    isSpicy: false,
  },
  {
    id: '10',
    name: 'Palak Paneer',
    type: 'Spinach Cottage Cheese',
    price: '$9.99',
    rating: 4.5,
    image: require('../assets/biryani2.jpg'),
    category: 'Veg Curries',
    description: 'Fresh spinach curry with soft paneer cubes in a creamy gravy.',
    ingredients: ['Spinach', 'Paneer', 'Onions', 'Tomatoes', 'Cream', 'Spices'],
    prepTime: '25 mins',
    serves: '2-3 people',
    calories: '280 per serving',
    isVeg: true,
    isSpicy: false,
  },

  // Non Veg Curries
  {
    id: '11',
    name: 'Butter Chicken',
    type: 'Creamy Tomato Curry',
    price: '$13.99',
    rating: 4.8,
    image: require('../assets/biryani3.jpg'),
    category: 'Non Veg Curries',
    description: 'Tender chicken in a rich, creamy tomato-based curry with butter and cream.',
    ingredients: ['Chicken', 'Tomatoes', 'Butter', 'Cream', 'Fenugreek', 'Spices'],
    prepTime: '35 mins',
    serves: '2-3 people',
    calories: '420 per serving',
    isVeg: false,
    isSpicy: false,
  },
  {
    id: '12',
    name: 'Mutton Curry',
    type: 'Traditional Style',
    price: '$16.99',
    rating: 4.7,
    image: require('../assets/biryani4.jpg'),
    category: 'Non Veg Curries',
    description: 'Slow-cooked mutton in a rich, spicy gravy with traditional spices.',
    ingredients: ['Mutton', 'Onions', 'Tomatoes', 'Yogurt', 'Red Chili', 'Garam Masala'],
    prepTime: '60 mins',
    serves: '2-3 people',
    calories: '480 per serving',
    isVeg: false,
    isSpicy: true,
  },

  // Tandoori and Kebabs
  {
    id: '13',
    name: 'Tandoori Chicken',
    type: 'Half Chicken',
    price: '$14.99',
    rating: 4.9,
    image: require('../assets/biryani1.jpg'),
    category: 'Tandoori and Kebabs',
    description: 'Half chicken marinated in yogurt and spices, cooked in tandoor oven.',
    ingredients: ['Chicken', 'Yogurt', 'Tandoori Masala', 'Lemon', 'Ginger-Garlic'],
    prepTime: '45 mins',
    serves: '2 people',
    calories: '380 per serving',
    isVeg: false,
    isSpicy: true,
  },
  {
    id: '14',
    name: 'Seekh Kebab',
    type: 'Minced Meat Skewers',
    price: '$12.99',
    rating: 4.6,
    image: require('../assets/biryani2.jpg'),
    category: 'Tandoori and Kebabs',
    description: 'Spiced minced meat shaped on skewers and grilled in tandoor.',
    ingredients: ['Minced Meat', 'Onions', 'Green Chili', 'Coriander', 'Spices'],
    prepTime: '30 mins',
    serves: '2-3 people',
    calories: '320 per serving',
    isVeg: false,
    isSpicy: true,
  },

  // Bread
  {
    id: '15',
    name: 'Naan',
    type: 'Plain Bread',
    price: '$2.99',
    rating: 4.3,
    image: require('../assets/biryani3.jpg'),
    category: 'Bread',
    description: 'Soft, fluffy Indian bread baked in tandoor oven.',
    ingredients: ['Flour', 'Yogurt', 'Yeast', 'Salt', 'Oil'],
    prepTime: '15 mins',
    serves: '1-2 people',
    calories: '150 per piece',
    isVeg: true,
    isSpicy: false,
  },
  {
    id: '16',
    name: 'Garlic Naan',
    type: 'Garlic Flavored',
    price: '$3.99',
    rating: 4.5,
    image: require('../assets/biryani4.jpg'),
    category: 'Bread',
    description: 'Naan bread topped with fresh garlic and coriander.',
    ingredients: ['Flour', 'Garlic', 'Coriander', 'Butter', 'Yogurt'],
    prepTime: '15 mins',
    serves: '1-2 people',
    calories: '180 per piece',
    isVeg: true,
    isSpicy: false,
  },

  // Beverages
  {
    id: '17',
    name: 'Mango Lassi',
    type: 'Sweet Yogurt Drink',
    price: '$4.99',
    rating: 4.4,
    image: require('../assets/biryani1.jpg'),
    category: 'Beverages',
    description: 'Refreshing yogurt-based drink blended with sweet mango pulp.',
    ingredients: ['Yogurt', 'Mango Pulp', 'Sugar', 'Cardamom'],
    prepTime: '5 mins',
    serves: '1 person',
    calories: '180 per glass',
    isVeg: true,
    isSpicy: false,
  },
  {
    id: '18',
    name: 'Masala Chai',
    type: 'Spiced Tea',
    price: '$2.99',
    rating: 4.2,
    image: require('../assets/biryani2.jpg'),
    category: 'Beverages',
    description: 'Traditional Indian tea brewed with aromatic spices and milk.',
    ingredients: ['Tea', 'Milk', 'Cardamom', 'Ginger', 'Cinnamon'],
    prepTime: '10 mins',
    serves: '1 person',
    calories: '120 per cup',
    isVeg: true,
    isSpicy: false,
  },

  // Desserts
  {
    id: '19',
    name: 'Gulab Jamun',
    type: 'Sweet Dumplings',
    price: '$5.99',
    rating: 4.6,
    image: require('../assets/biryani3.jpg'),
    category: 'Desserts',
    description: 'Soft, spongy dumplings soaked in rose-flavored sugar syrup.',
    ingredients: ['Milk Powder', 'Flour', 'Sugar', 'Rose Water', 'Cardamom'],
    prepTime: '20 mins',
    serves: '2-3 people',
    calories: '250 per serving',
    isVeg: true,
    isSpicy: false,
  },
  {
    id: '20',
    name: 'Kulfi',
    type: 'Indian Ice Cream',
    price: '$4.99',
    rating: 4.4,
    image: require('../assets/biryani4.jpg'),
    category: 'Desserts',
    description: 'Traditional Indian ice cream flavored with cardamom and pistachios.',
    ingredients: ['Milk', 'Sugar', 'Cardamom', 'Pistachios', 'Almonds'],
    prepTime: '5 mins',
    serves: '1 person',
    calories: '200 per serving',
    isVeg: true,
    isSpicy: false,
  },
];